version: '3'
services:
  neo4j:
    container_name: nest-movies-neo4j
    image: neo4j:5.3.0-community
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.import.file.use_neo4j_config=true
    ports:
      - 7474:7474
      - 7687:7687
